table fact_order_payments
	lineageTag: 11e8fae0-4aa5-4ebc-8c6b-42597020ad8e

	column customer_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7f7ca0a6-d8b3-4f8a-b85e-a8fe3cd44d27
		summarizeBy: none
		sourceColumn: customer_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column payment_type_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 04d62b65-788a-4a6a-b117-c342db6c58b3
		summarizeBy: none
		sourceColumn: payment_type_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ID заказа'
		dataType: string
		lineageTag: 32fc0188-6121-4329-83f3-fb58a393b852
		summarizeBy: none
		sourceColumn: ID заказа

		annotation SummarizationSetBy = Automatic

	column 'Номер платежа в заказе'
		dataType: int64
		formatString: 0
		lineageTag: a0e90cfa-4ef3-46a4-8e73-ffa2a2a4b56d
		summarizeBy: none
		sourceColumn: Номер платежа в заказе

		annotation SummarizationSetBy = User

	column 'Количество долей оплаты'
		dataType: int64
		formatString: 0
		lineageTag: 5a029ae1-d173-4a48-8058-aa3308552c21
		summarizeBy: none
		sourceColumn: Количество долей оплаты

		annotation SummarizationSetBy = User

	column 'Полная сумма заказа'
		dataType: double
		lineageTag: 2109f94b-8d89-4dbb-ab22-df5bef334e87
		summarizeBy: sum
		sourceColumn: Полная сумма заказа

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Дата создания заказа'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b1ed3979-6d03-4bd1-b900-0cbb389a7fb3
		summarizeBy: none
		sourceColumn: Дата создания заказа

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Дата подтверждения заказа'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6f67e710-910d-496b-82b2-605cc2ac127f
		summarizeBy: none
		sourceColumn: Дата подтверждения заказа

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition fact_order_payments = m
		mode: import
		queryGroup: 3_Facts
		source =
				let
				    Источник = #"gold fact_mart",
				    #"Объединенные запросы" = Table.NestedJoin(Источник, {"order_status"}, dim_order_status, {"Статус заказа"}, "dim_order_status", JoinKind.LeftOuter),
				    #"Развернутый элемент dim_order_status" = Table.ExpandTableColumn(#"Объединенные запросы", "dim_order_status", {"order_status_key"}, {"order_status_key"}),
				    #"Переупорядоченные столбцы" = Table.ReorderColumns(#"Развернутый элемент dim_order_status",{"customer_key", "product_key", "seller_key", "order_status_key", "order_id", "order_item_id", "payment_type", "payment_sequential", "payment_installments", "price", "freight_value", "payment_value", "order_status", "shipping_limit_date", "order_purchase_date", "order_approved_at", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"}),
				    #"Удаленные столбцы" = Table.RemoveColumns(#"Переупорядоченные столбцы",{"order_status"}),
				    #"Объединенные запросы1" = Table.NestedJoin(#"Удаленные столбцы", {"payment_type"}, dim_payment_type, {"Тип оплаты"}, "dim_payment_type", JoinKind.LeftOuter),
				    #"Развернутый элемент dim_payment_type" = Table.ExpandTableColumn(#"Объединенные запросы1", "dim_payment_type", {"payment_type_key"}, {"payment_type_key"}),
				    #"Переупорядоченные столбцы1" = Table.ReorderColumns(#"Развернутый элемент dim_payment_type",{"customer_key", "product_key", "seller_key", "order_status_key", "order_id", "payment_type_key", "order_item_id", "payment_type", "payment_sequential", "payment_installments", "price", "freight_value", "payment_value", "shipping_limit_date", "order_purchase_date", "order_approved_at", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"}),
				    #"Удаленные столбцы1" = Table.RemoveColumns(#"Переупорядоченные столбцы1",{"payment_type"}),
				    #"Переупорядоченные столбцы2" = Table.ReorderColumns(#"Удаленные столбцы1",{"customer_key", "product_key", "seller_key", "order_status_key", "payment_type_key", "order_id", "order_item_id", "payment_sequential", "payment_installments", "price", "freight_value", "payment_value", "shipping_limit_date", "order_purchase_date", "order_approved_at", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"}),
				    #"Удаленные столбцы2" = Table.RemoveColumns(#"Переупорядоченные столбцы2",{"product_key", "seller_key", "order_status_key", "price", "freight_value", "order_item_id", "shipping_limit_date", "order_delivered_carrier_date", "order_delivered_customer_date", "order_estimated_delivery_date"}),
				    #"Удаленные дубликаты" = Table.Distinct(#"Удаленные столбцы2"),
				    #"Переименованные столбцы" = Table.RenameColumns(#"Удаленные дубликаты",{{"payment_value", "Полная сумма заказа"}, {"order_purchase_date", "Дата создания заказа"}, {"order_id", "ID заказа"}, {"order_approved_at", "Дата подтверждения заказа"}, {"payment_installments", "Количество долей оплаты"}, {"payment_sequential", "Номер платежа в заказе"}})
				in
				    #"Переименованные столбцы"

	annotation PBI_NavigationStepName = Навигация

	annotation PBI_ResultType = Table

